language: node_js
sudo: false
node_js:
  - 8
  - 14
  - 15
  - node

arch:
  - amd64
  - ppc64le

script:
  - npm install phantomjs-prebuilt@2.1.16 --ignore-scripts

after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
